#!/bin/bash

bindgen bindings.h -o src/bindings.rs \
--distrust-clang-mangling \
--no-layout-tests \
--no-recursive-whitelist \
--no-prepend-enum-name \
--raw-line "use {c_float, c_int};" \
--whitelist-type csc \
--whitelist-type LinSysSolver \
--whitelist-type OSQPScaling \
--whitelist-type OSQPSolution \
--whitelist-type OSQPInfo \
--whitelist-type OSQPPolish \
--whitelist-type OSQPData \
--whitelist-type OSQPSettings \
--whitelist-type OSQPWorkspace \
--whitelist-type OSQPSolver \
--whitelist-type linsys_solver \
--whitelist-type osqp_linsys_solver_type \
--whitelist-type osqp_error_type \
--whitelist-type osqp_status_type \
--whitelist-function osqp_setup \
--whitelist-function osqp_solve \
--whitelist-function osqp_cleanup \
--whitelist-function osqp_warm_start \
--whitelist-function osqp_warm_start_x \
--whitelist-function osqp_warm_start_y \
--whitelist-function osqp_update_settings \
--whitelist-function osqp_update_rho \
--whitelist-function osqp_update_data_vec \
--whitelist-function osqp_update_data_mat \
--whitelist-function osqp_set_default_settings \
--opaque-type OSQPWorkspace
